"""corrections to relationships are done

Revision ID: b1a54f6f5770
Revises: aac919611d9f
Create Date: 2023-06-19 01:39:17.484870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a54f6f5770'
down_revision = 'aac919611d9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
