"""id_pack deleted from truth and dare

Revision ID: aac919611d9f
Revises: 6727cbb7efaa
Create Date: 2023-06-18 05:52:58.453350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac919611d9f'
down_revision = '6727cbb7efaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dare_id_pack_fkey', 'dare', type_='foreignkey')
    op.drop_column('dare', 'id_pack')
    op.drop_constraint('truth_id_pack_fkey', 'truth', type_='foreignkey')
    op.drop_column('truth', 'id_pack')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('truth', sa.Column('id_pack', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('truth_id_pack_fkey', 'truth', 'pack', ['id_pack'], ['id_pack'])
    op.add_column('dare', sa.Column('id_pack', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('dare_id_pack_fkey', 'dare', 'pack', ['id_pack'], ['id_pack'])
    # ### end Alembic commands ###
