"""New relations

Revision ID: 6727cbb7efaa
Revises: 661ece13048d
Create Date: 2023-06-18 05:45:08.281358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6727cbb7efaa'
down_revision = '661ece13048d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dare', 'id_pack',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('truth', 'id_pack',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('truth', 'id_pack',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dare', 'id_pack',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
