"""Truths and dares now have user

Revision ID: 661ece13048d
Revises: 2935d6334933
Create Date: 2023-06-17 23:56:29.516896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661ece13048d'
down_revision = '2935d6334933'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dare', sa.Column('id_user', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'dare', 'user', ['id_user'], ['id'])
    op.add_column('truth', sa.Column('id_user', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'truth', 'user', ['id_user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'truth', type_='foreignkey')
    op.drop_column('truth', 'id_user')
    op.drop_constraint(None, 'dare', type_='foreignkey')
    op.drop_column('dare', 'id_user')
    # ### end Alembic commands ###
