"""Corrections Player

Revision ID: 771576db1255
Revises: 9f65cfa77657
Create Date: 2023-06-16 01:40:10.439927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771576db1255'
down_revision = '9f65cfa77657'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
