"""Database creation

Revision ID: 8b47596504b7
Revises: 
Create Date: 2023-06-12 01:19:03.501894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b47596504b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Player',
                    sa.Column('id_player', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id_player')
    )
    op.create_table('Pack',
                    sa.Column('id_pack', sa.Integer(), nullable=False),
                    sa.Column('packname', sa.String(), nullable=False),
                    sa.Column('id_player', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['id_player'], ['Player.id_player'], ),
                    sa.PrimaryKeyConstraint('id_pack')
    )
    op.create_table('Dare',
                    sa.Column('id_dare', sa.Integer(), nullable=False),
                    sa.Column('text', sa.String(length=255), nullable=False),
                    sa.Column('id_pack', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['id_pack'], ['Pack.id_pack'], ),
                    sa.PrimaryKeyConstraint('id_dare')
    )
    op.create_table('Truth',
                    sa.Column('id_truth', sa.Integer(), nullable=False),
                    sa.Column('text', sa.String(length=255), nullable=False),
                    sa.Column('id_pack', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['id_pack'], ['Pack.id_pack'], ),
                    sa.PrimaryKeyConstraint('id_truth')
    )
    op.create_table('Dare_Pack',
                    sa.Column('id_pack', sa.Integer(), nullable=False),
                    sa.Column('id_dare', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['id_dare'], ['Dare.id_dare'], ),
                    sa.ForeignKeyConstraint(['id_pack'], ['Pack.id_pack'], ),
                    sa.PrimaryKeyConstraint('id_pack', 'id_dare')
    )
    op.create_table('Truth_Pack',
                    sa.Column('id_pack', sa.Integer(), nullable=False),
                    sa.Column('id_truth', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['id_pack'], ['Pack.id_pack'], ),
                    sa.ForeignKeyConstraint(['id_truth'], ['Truth.id_truth'], ),
                    sa.PrimaryKeyConstraint('id_pack')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Truth_Pack')
    op.drop_table('Dare_Pack')
    op.drop_table('Truth')
    op.drop_table('Dare')
    op.drop_table('Pack')
    op.drop_table('Player')
    # ### end Alembic commands ###
