"""Updated table

Revision ID: 9f65cfa77657
Revises: 8b47596504b7
Create Date: 2023-06-16 01:37:41.438148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f65cfa77657'
down_revision = '8b47596504b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Player', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('Player', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('Player', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('Player', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_column('Player', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Player', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Player', 'is_verified')
    op.drop_column('Player', 'is_superuser')
    op.drop_column('Player', 'is_active')
    op.drop_column('Player', 'hashed_password')
    # ### end Alembic commands ###
