"""Relations updated

Revision ID: dbc61a248e91
Revises: 661ece13048d
Create Date: 2023-06-18 01:17:18.476007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbc61a248e91'
down_revision = '661ece13048d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dare', 'id_dare',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('dare', 'id_pack',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pack', 'id_pack',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True,
               existing_server_default=sa.text("nextval('pack_id_pack_seq'::regclass)"))
    op.alter_column('truth', 'id_truth',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True,
               existing_server_default=sa.text("nextval('user_id_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('user_id_seq'::regclass)"))
    op.alter_column('truth', 'id_truth',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('pack', 'id_pack',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('pack_id_pack_seq'::regclass)"))
    op.alter_column('dare', 'id_pack',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dare', 'id_dare',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
