from connection import *


create_tables = """
DROP TABLE IF EXISTS TRUTH_PACK;
DROP TABLE IF EXISTS DARE_PACK;
DROP TABLE IF EXISTS PACK;
DROP TABLE IF EXISTS PLAYER;
DROP TABLE IF EXISTS TRUTH;
DROP TABLE IF EXISTS DARE;

CREATE TABLE PLAYER (
    IDPLAYER INTEGER,
    USERNAME VARCHAR(20),
    PASSWORD VARCHAR(50),
    PRIMARY KEY (IDPLAYER)
);

CREATE TABLE TRUTH (
    IDTRUTH INTEGER,
    TEXT VARCHAR(150),
    PRIMARY KEY(IDTRUTH)
);

CREATE TABLE DARE (
    IDDARE INTEGER,
    TEXT VARCHAR(150),
    PRIMARY KEY(IDDARE)
);

CREATE TABLE PACK (
    IDPACK INTEGER,
    PACKNAME VARCHAR(50),
    IDPLAYER INTEGER,
    PRIMARY KEY (IDPACK),
    CONSTRAINT fk_player
        FOREIGN KEY (IDPLAYER)
            REFERENCES PLAYER (IDPLAYER)
);

CREATE TABLE TRUTH_PACK (
    IDTRUTH INTEGER REFERENCES TRUTH (IDTRUTH) ON UPDATE CASCADE ON DELETE CASCADE ,
    IDPACK INTEGER REFERENCES PACK (IDPACK) ON UPDATE CASCADE ON DELETE CASCADE ,
    CONSTRAINT TRUTH_PACK_PK PRIMARY KEY (IDTRUTH, IDPACK)
);

CREATE TABLE DARE_PACK (
    IDDARE INTEGER REFERENCES DARE (IDDARE) ON UPDATE CASCADE ON DELETE CASCADE ,
    IDPACK INTEGER REFERENCES PACK (IDPACK) ON UPDATE CASCADE ON DELETE CASCADE ,
    CONSTRAINT DARE_PACK_PK PRIMARY KEY (IDDARE, IDPACK)
);
"""

connection.exec_driver_sql(create_tables)


connection.commit()


connection.close()
